### ISSUE TITLE
What are the dependencies for MathJax-mhchem?

### ISSUE THREAD

**Issue by Shahxad-Akram** [mhchem/MathJax-mhchem#12]
What are the actual dependencies for MathJax-mhchem from MathJax library? I am using minified version of MathJax from [here](https://github.com/electricbookworks/mini-mathjax).  Its working fine but not with this extension. I want to use this for mobile app development so MathJax is a huge library to work with therefore I am using minified version.

**Comment by mhchem** [comment]
I don't know the details of the mini-MathJax project. You can of course strip doc, unpacked, etc. Leave in the output variants you need. Leave in the TeX input. Try TeX. If that works, include (or enable) mhchem and everything should work fine.
