### ISSUE TITLE
There are plans to support mathjax3 ?

### ISSUE THREAD

**Issue by MonoLogueChi** [mhchem/MathJax-mhchem#17]
mhchem now does not seem to work on mathjax3

**Comment by mhchem** [comment]
Oh, it is supported. It is even baked-in, no need to load an extension from another URL, see http://docs.mathjax.org/en/latest/input/tex/extensions/mhchem.html

Now, that MathJax 3 is being used by more and more people, it is probably a good time to update the documentation. Then, I would need to clean up this repository, but I'd rather wait till I see MathJax3 being used in the wild.

**Comment by MonoLogueChi** [comment]
Thanks, I have not noticed the document. I suggest you update about the README, may be more than one person I do not know how to use mhchem in MathJax3 in. And README documents in connection now points to an error page
