### ISSUE TITLE
How to write on the equal sign？

### ISSUE THREAD

**Issue by yangshiju** [mhchem/MathJax-mhchem#19]
i want to write on the equal sign.like $\ce{A ->[{text above}][{text below}] B}$, replace -> to =.
![data#9_img_from_word#2231_image8](https://user-images.githubusercontent.com/44403275/110413522-f8263480-80c8-11eb-810c-0b111a4941fd.png)

**Comment by mhchem** [comment]
You can switch to math mode and use `\stackrel`.

    \ce{A $\stackrel{\text{text above}}{=}$ B}

I've never seen a stretchy equal sign. I think, this doesn't really exist, like a plus or minus sign also isn't stretchy.
