### ISSUE TITLE
Arrow <=> not in correct size when "ui/safe" is enabled

### ISSUE THREAD

**Issue by abnerlee** [mhchem/MathJax-mhchem#21]
See https://jsbin.com/cadobasoho/edit?html,js,console,output

Example HTML:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>MathJax + mhchem example</title>
  <script>
    window.MathJax = {
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']],
        packages: {'[+]': ['mhchem']}
      },
      loader: {load: ['[tex]/mhchem', 'ui/safe']},
    };
  </script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js"></script>
</head>
<body>
  $\ce{<=>}$
</body>
</html>
```

In the rendered result, the upper arrow is shorter than the bottom arrow.

But if I remove "ui/safe", it looks fine.

**Comment by mhchem** [comment]
Thanks for reporting this and for doing the analysis that this is caused by ui/safe. I removed mhchem from the minimum example and forwarded this bug to the MathJax folks, see link above.
