### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by pkra** [mhchem/MathJax-mhchem#5]
Once https://github.com/mathjax/MathJax-node/pull/391 lands, it would be great to be able to pull in mhchem from npm.

**Comment by mhchem** [comment]
Will this do? https://www.npmjs.com/package/mathjax-mhchem

**Comment by pkra** [comment]
Oh, did I miss this before or did you just publish it? In any case, thank you!

**Comment by mhchem** [comment]
I quickly published it after reading your request. I hope I did everything correctly.

**Comment by pkra** [comment]
> I quickly published it after reading your request. I hope I did everything correctly.

Ah! That makes sense then. The only thing that surprised me was that mathjax was a dependency (which makes sense but isn't listed in the repo's package.json).

Thanks again for the quick fix!

**Comment by mhchem** [comment]
> The only thing that surprised me was that mathjax was a dependency (which makes sense but isn't listed in the repo's package.json).

That's easy: The package.json on GitHub is a few hours older than the one on npm.

**Comment by pkra** [comment]
> That's easy: The package.json on GitHub is a few hours older than the one on npm.

I figured :smile:
