### ISSUE TITLE
Wrong interpretation of vapour phase symbol

### ISSUE THREAD

**Issue by polyluxus** [mhchem/MathJax-mhchem#6]
Currently the engine interprets the state of aggregation indicated with a v as a downward arrow for precipitation, i.e. `\ce{H2O (v)}` = H<sub>2</sub>O ↓, it should be H<sub>2</sub>O(v) instead. I think in general the usage of 'v' is not standard, it should be 'g' instead, it might be good to support states of aggregation as a special rule, given that they are set in parenthesis. See the Green Book ([pdf](http://iupac.org/cms/wp-content/uploads/2015/07/Green-Book-PDF-Version-2011.pdf)) p. 54.

**Comment by mhchem** [comment]
I am not sure how to help you there. You do yourself link to the definition of states of aggregations and 'v' is not among them. Furthermore, 'v' is the best substitute for downward arrow, a normal keyboard has. I wouldn't feel good to change the precipitate syntax (that has been around for a decade) for something nonstandard.

**Comment by polyluxus** [comment]
Yes it is not standard, but it had to come from somewhere, I stumbled upon it while editing some questions. In any case, I can find any reference back to that. I do not find any reference to those arrows either.  
I guess in general I did not expect that constructs in parenthesis would be parsed in that specific way.
